from mylib.regularizations._Regularization import Regularization

from mylib.regularizations.RidgeRegularization import RidgeRegularization
from mylib.regularizations.LassoRegularization import LassoRegularization
from mylib.regularizations.ElasticNetRegularization import ElasticNetRegularization